apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: example-pipeline
spec:
  resources:
  - name: git
    type: git
  tasks:
  - name: example-task
    taskRef:
      name: example-task
    resources:
      inputs:
      - name: git
        resource: git
