apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: example-task-run
spec:
  resources:
    inputs:
    - name: git
      resourceRef:
        name: example-git
  taskRef:
    name: example-task
