apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: example-task
spec:
  resources:
    inputs:
    - name: git
      type: git
  steps:
  - name: pytest
    image: python
    script: |
      #!/bin/bash
      cd /workspace/git/tutorials/katacoda/runs/src/app
      pip install -r requirements.txt
      pip install -r dev_requirements.txt
      pytest .
